### ISSUE TITLE
Feature Request: English number.

### ISSUE THREAD

**Issue by bleedweedsuz** [sajanm/nepali-date-picker#1]
Current version I saw that there is no feature for English Number in the calendar, only Nepali number is visible. Is there is possible to change those number to English.

![date](https://user-images.githubusercontent.com/10117919/106377494-76eeca00-63c5-11eb-9f5e-3f0e62c18043.png)

**Comment by sajanm** [comment]
The english calendar view has been added. 

Use Option:
{
    language: "english"
}

Example:
http://nepalidatepicker.sajanmaharjan.com.np/#languageEnglish
