### ISSUE TITLE
month and year select option not working.

### ISSUE THREAD

**Issue by puru47** [sajanm/nepali-date-picker#3]
month and year select option not working with class selector on v3.7. It only works with id selector.

example - 
$('.date_np').nepaliDatePicker({
    ndpYear: true,
    ndpMonth: true,
    ndpYearCount: 10
});

**Comment by sajanm** [comment]
The code is working fine. 

Please find the working copy here:
https://plnkr.co/plunk/IpKqzD5IuZ1FhNXS
